---
# we use docker as plateform
driver:
  name: vagrant

# Ansible will be our provisioner
provisioner:
  name: ansible_playbook
  hosts: localhost
  require_chef_for_busser: false
  require_ruby_for_busser: false
  require_ansible_omnibus: false

platforms:
  - name: centos-7

# We use Inspec as testing framework
verifier:
  name: inspec
  inspec_tests:
    - path: tests/inspec

# Define playbook
suites:
  - name: pci-dss
    provisioner:
      name: ansible_playbook
      playbook: tests/test.yml
      extra_vars:
        security_standard: "pci-dss"
  - name: rht-ccp
    provisioner:
      name: ansible_playbook
      playbook: tests/test.yml
      extra_vars:
        security_standard: "rht-ccp"
  - name: stig-rhel7
    provisioner:
      name: ansible_playbook
      playbook: tests/test.yml
      extra_vars:
        security_standard: "stig-rhel7"
