---
# tasks file for main

- import_tasks: audit.yml
  tags:
    - audit

- import_tasks: filesystem.yml
  tags:
    - filesystem

- import_tasks: firewalld.yml
  tags:
    - firewalld
  when: ansible_virtualization_type != 'docker'

- import_tasks: kernel.yml
  tags:
    - kernel

- import_tasks: yum.yml
  tags:
    - yum
  when: ansible_os_family == 'RedHat'

- import_tasks: pam.yml
  tags:
    - pam

- import_tasks: selinux.yml
  tags:
    - selinux

- import_tasks: services/aide.yml
  tags:
    - aide

- import_tasks: services/ntp.yml
  tags:
    - ntp

- import_tasks: services/sshd.yml
  tags:
    - sshd
