---
# tasks file for packages

- name: Install libreswan for IPsec
  yum:
    name: libreswan
    state: latest
    update_cache: yes

- name: yum update
  yum:
    name: "*"
    state: latest
    update_cache: yes
